---
version: '2.1'

services:

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - JELLYFIN_PublishedServerUrl=192.168.0.111 #optional
    volumes:
      - /home/jellyfin/config:/config
      - /home/downloads/videos:/data/videos
      - /home/downloads/show:/data/show
      - /home/downloads/anime:/data/anime
      - /home/downloads/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
